# Generated by Django 4.2.19 on 2025-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updates_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
